# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA07/MinhTuong/python-app/ui/listening.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 793)
        MainWindow.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(50, 30, 441, 681))
        self.main_frame.setStyleSheet("background-color:rgb(40, 40, 40);\n"
"border-radius: 10px;")
        self.main_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_frame.setObjectName("main_frame")
        self.listenning_to_label = QtWidgets.QLabel(parent=self.main_frame)
        self.listenning_to_label.setGeometry(QtCore.QRect(10, 10, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(22)
        self.listenning_to_label.setFont(font)
        self.listenning_to_label.setStyleSheet("color:rgb(145, 145, 145);")
        self.listenning_to_label.setObjectName("listenning_to_label")
        self.pause_btn = QtWidgets.QPushButton(parent=self.main_frame)
        self.pause_btn.setGeometry(QtCore.QRect(170, 590, 93, 81))
        self.pause_btn.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.pause_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/MinhTuong/python-app/ui/../img/images.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pause_btn.setIcon(icon)
        self.pause_btn.setObjectName("pause_btn")
        self.process_bar_frame = QtWidgets.QFrame(parent=self.main_frame)
        self.process_bar_frame.setGeometry(QtCore.QRect(20, 540, 401, 41))
        self.process_bar_frame.setStyleSheet("background-color:rgb(72, 72, 72)")
        self.process_bar_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.process_bar_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.process_bar_frame.setObjectName("process_bar_frame")
        self.progress_bar = QtWidgets.QSlider(parent=self.process_bar_frame)
        self.progress_bar.setGeometry(QtCore.QRect(10, 10, 381, 22))
        self.progress_bar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.progress_bar.setObjectName("progress_bar")
        self.lyrics_label = QtWidgets.QLabel(parent=self.main_frame)
        self.lyrics_label.setGeometry(QtCore.QRect(20, 394, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(22)
        self.lyrics_label.setFont(font)
        self.lyrics_label.setStyleSheet("color:rgb(145, 145, 145);")
        self.lyrics_label.setObjectName("lyrics_label")
        self.music_icon = QtWidgets.QFrame(parent=self.main_frame)
        self.music_icon.setGeometry(QtCore.QRect(90, 70, 250, 250))
        self.music_icon.setStyleSheet("background-color:rgb(72, 72, 72)")
        self.music_icon.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.music_icon.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.music_icon.setObjectName("music_icon")
        self.song_name_label = QtWidgets.QLabel(parent=self.main_frame)
        self.song_name_label.setGeometry(QtCore.QRect(30, 330, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(18)
        self.song_name_label.setFont(font)
        self.song_name_label.setStyleSheet("color:rgb(145, 145, 145);\n"
"")
        self.song_name_label.setObjectName("song_name_label")
        self.song_name_label_2 = QtWidgets.QLabel(parent=self.main_frame)
        self.song_name_label_2.setGeometry(QtCore.QRect(20, 450, 381, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(13)
        self.song_name_label_2.setFont(font)
        self.song_name_label_2.setStyleSheet("color:rgb(145, 145, 145);\n"
"")
        self.song_name_label_2.setObjectName("song_name_label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 541, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.listenning_to_label.setText(_translate("MainWindow", "Listening to:"))
        self.lyrics_label.setText(_translate("MainWindow", "Lyrics:"))
        self.song_name_label.setText(_translate("MainWindow", "Song name"))
        self.song_name_label_2.setText(_translate("MainWindow", "Playing lyrics"))
