# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA07/MinhTuong/python-app/ui/playlist.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 713)
        MainWindow.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.background_frame.setGeometry(QtCore.QRect(20, 0, 741, 651))
        self.background_frame.setStyleSheet("background-color:rgb(92, 92, 92);\n"
"border-radius:40px;")
        self.background_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.background_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.background_frame.setObjectName("background_frame")
        self.playlist_name = QtWidgets.QLabel(parent=self.background_frame)
        self.playlist_name.setGeometry(QtCore.QRect(20, 20, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(30)
        self.playlist_name.setFont(font)
        self.playlist_name.setStyleSheet("background-color:rgb(171, 171, 171);\n"
"border-radius: 15px;\n"
"color: rgb(0, 0, 0);")
        self.playlist_name.setObjectName("playlist_name")
        self.background_frame_2 = QtWidgets.QFrame(parent=self.background_frame)
        self.background_frame_2.setGeometry(QtCore.QRect(10, 120, 701, 81))
        self.background_frame_2.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border-radius:40px;")
        self.background_frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.background_frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.background_frame_2.setObjectName("background_frame_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.background_frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 10, 81, 61))
        self.pushButton_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/MinhTuong/python-app/ui/../img/plus-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(parent=self.background_frame_2)
        self.label.setGeometry(QtCore.QRect(120, 0, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.background_frame_2)
        self.label_2.setGeometry(QtCore.QRect(120, 40, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.playlist_name.setText(_translate("MainWindow", "Name"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "Artist"))
